window.MAISTER_DATA = {
  generated: "2026-07-04T16:55:56Z",
  task: {
    title: "Learn Mode respects Browse's filtered subset",
    type: "product-design",
    status: "completed",
    description: "Learn Mode should draw only from the subset of glossary entries currently filtered in Browse (category/level/search), and that filter selection should be remembered locally in the browser across sessions.",
    path: ".maister/tasks/product-design/2026-07-04-learn-filtered-subset",
    current_activity: null
  },
  characteristics: {
    is_greenfield: false,
    is_enhancement: true,
    is_ui_focused: true,
    is_backend: false,
    is_complex: false,
    is_simple: false
  },
  phases: [
    {id: "phase-0", name: "Initialize, gather context & detect characteristics", icon_hint: "analysis", status: "completed", started: "2026-07-04T15:01:22Z", completed: "2026-07-04T15:05:28Z", skip_reason: null, summary: "Enhancement, UI-focused, not backend, Standard complexity — confirmed by user, no additional context provided.", decisions: [{decision: "Design characteristics: Enhancement, UI-focused, not backend, Standard complexity", rationale: "Confirmed by user without changes"}], risks: [], artifacts: [], gate: {question: "Do the detected design characteristics match your intent?", answer: "Correct, proceed"}},
    {id: "phase-1", name: "Synthesize all context sources", icon_hint: "analysis", status: "completed", started: "2026-07-04T15:05:28Z", completed: "2026-07-04T15:15:50Z", skip_reason: null, summary: "Browse's filter state is component-local and never persisted today; Learn Mode always draws from the full glossary. The pure-logic layer (applyFilters/drawNextCard) needs no changes — this is a state-lift-up + persistence wiring task, recommended at AppShell.", decisions: [], risks: ["Reverses a documented prior decision: feature-spec.md explicitly ruled out filter persistence and kept Browse/Learn Mode decoupled — needs conscious re-confirmation, not silent override.", "Empty-subset edge case (filter matches 0 entries) is undefined and needs a Phase 2/6 decision.", "Learn progress is keyed by entry id, not by filter, so progress persists across filter changes — likely correct but should be an explicit decision."], artifacts: [{path: "analysis/codebase-analysis.md", label: "Codebase Analysis", html: null}, {path: "analysis/design-context.md", label: "Unified Design Context", html: null}], gate: {question: "Any corrections or additions to the context synthesis before we explore the problem space?", answer: "Accurate, proceed"}},
    {id: "phase-2", name: "Explore problem space", icon_hint: "analysis", status: "completed", started: "2026-07-04T15:15:50Z", completed: "2026-07-04T15:26:27Z", skip_reason: null, summary: "Learn Mode should draw only from Browse's active category/level filter, persisted in localStorage across sessions (search excluded) — reverses the original decoupled-views decision, deliberately.", decisions: [{decision: "Persist via localStorage, not cookies", rationale: "Matches existing storage.ts convention exactly"}, {decision: "Only category + level persist, not search text", rationale: "Category/level are a durable topic-subset choice; search is a one-off tool"}, {decision: "Automatic sync between Browse filter and Learn Mode", rationale: "Zero extra steps — set filter once, Learn Mode reflects it"}, {decision: "Empty-subset shows empty state with broaden action", rationale: "Consistent with Browse's existing pattern"}, {decision: "Learn Mode shows active-filter indicator + quick clear", rationale: "Avoids confusion; avoids forcing a trip back to Browse"}], risks: ["Reverses a documented prior product decision — confirmed deliberately with the requester", "Learn progress persists across filter changes (keyed by entry id) — confirmed as intended"], artifacts: [{path: "analysis/problem-statement.md", label: "Problem Statement", html: null}], gate: {question: "Does this problem statement, constraints, and success criteria capture the design correctly?", answer: "Approve and continue"}},
    {id: "phase-3", name: "Explore users & personas", icon_hint: "analysis", status: "skipped", started: null, completed: null, skip_reason: "Not greenfield/complex (Standard, Enhancement) — personas already established in the original design task apply unchanged.", summary: null, decisions: [], risks: [], artifacts: [], gate: null},
    {id: "phase-4", name: "Generate design alternatives", icon_hint: "plan", status: "completed", started: "2026-07-04T15:26:27Z", completed: "2026-07-04T15:57:10Z", skip_reason: null, summary: "4 decision areas (state lift-up, persistence schema, active-filter indicator, empty-subset handling), 3 alternatives each. All 4 recommended alternatives reuse existing patterns exactly.", decisions: [], risks: ["LearnMode.ts computes its draw pool only once at construction; will need an 'update in place' method to react to live filter changes — sizing question for Phase 6."], artifacts: [{path: "analysis/alternatives.md", label: "Solution Exploration", html: null}], gate: null},
    {id: "phase-5", name: "Converge on design direction", icon_hint: "plan", status: "completed", started: "2026-07-04T15:57:10Z", completed: "2026-07-04T16:24:41Z", skip_reason: null, summary: "AppShell-owned filter state + callbacks (1A); flat 2-field localStorage schema (2A); dismissible topbar chip in Learn Mode (3B); reuse Browse's empty-state pattern (4A).", decisions: [{decision: "1A: Lift BrowseFilterState to AppShell", rationale: "Matches existing activeTab precedent; no new architectural concepts"}, {decision: "2A: Flat 2-field persisted schema, search excluded at write", rationale: "Mirrors storage.ts exactly; enforces constraint structurally"}, {decision: "3B: Dismissible chip in Learn Mode's topbar", rationale: "Reuses existing chrome and icon-button pattern"}, {decision: "4A: Reuse Browse's empty-state pattern", rationale: "Zero new visual design, consistent with constraint wording"}], risks: ["LearnMode needs a new 'update in place' capability — small new surface, to be sized in Phase 6", "Topbar chip tap-to-jump-to-Browse behavior deferred as UX-polish detail to Phase 6/7"], artifacts: [{path: "analysis/design-decisions.md", label: "Design Decisions", html: "analysis/design-decisions.html"}], gate: {question: "Design direction approved. Continue to Feature Specification?", answer: "Continue to Phase 6"}},
    {id: "phase-6", name: "Specify features section-by-section", icon_hint: "spec", status: "completed", started: "2026-07-04T16:24:41Z", completed: "2026-07-04T16:34:14Z", skip_reason: null, summary: "6 sections: data model/persistence, state ownership/wiring, active-filter indicator, empty-subset handling, progress tracking/stats scoping, testing requirements. All implementation-ready.", decisions: [{decision: "AppShell is sole owner/mediator of filter state", rationale: "BrowseGrid and LearnMode remain mutually decoupled"}, {decision: "Persisted schema excludes searchQuery at the type level", rationale: "No field exists to accidentally serialize"}, {decision: "Active-filter indicator is a dismissible topbar chip", rationale: "Reuses existing icon-button/chip visual language"}, {decision: "Empty-state extracted into a shared EmptyState component", rationale: "DRY — reused by both BrowseGrid and LearnMode"}, {decision: "Progress stats scope to the active filtered subset", rationale: "More meaningful feedback for focused study sessions"}, {decision: "Progress persistence itself unaffected, still keyed by entry id", rationale: "Confirmed intended behavior from Phase 2"}], risks: [], artifacts: [{path: "analysis/feature-spec.md", label: "Feature Specification", html: "analysis/feature-spec.html"}], gate: {question: "Specification complete. Continue to Phase 7: Visual Prototyping?", answer: "Continue to Phase 7"}},
    {id: "phase-7", name: "Create visual prototypes", icon_hint: "code", status: "completed", started: "2026-07-04T16:34:14Z", completed: "2026-07-04T16:38:16Z", skip_reason: null, summary: "2 mockups via visual companion: Learn Mode with active-filter chip in topbar (scoped stats), and the empty-subset state reusing Browse's empty-state pattern. Both approved on first review.", decisions: [], risks: [], artifacts: [{path: "analysis/mockups/learn-mode-active-filter-chip.html", label: "Learn Mode — Active Filter Chip", html: "analysis/mockups/learn-mode-active-filter-chip.html"}, {path: "analysis/mockups/learn-mode-empty-filtered-subset.html", label: "Learn Mode — Empty Filtered Subset", html: "analysis/mockups/learn-mode-empty-filtered-subset.html"}], gate: {question: "Do these mockups look right?", answer: "Approve all screens and continue"}},
    {id: "phase-8", name: "Review & hand off product brief", icon_hint: "done", status: "completed", started: "2026-07-04T16:38:16Z", completed: "2026-07-04T16:55:56Z", skip_reason: null, summary: "Layered product brief assembled (Layer 1 personas omitted — Phase 3 skipped) and approved on first review. Visual companion server shut down.", decisions: [], risks: [], artifacts: [{path: "outputs/product-brief.md", label: "Product Brief", html: "outputs/product-brief.html"}], gate: {question: "Here's the assembled product brief — this is what will be handed off to development. Approve it?", answer: "Approve product brief"}}
  ],
  verification: { status: null, issues: [], fixes: [], reverify_count: 0 }
}
