window.MAISTER_DATA = {
  generated: "2026-07-13T14:07:40Z",
  task: {
    title: "Add new categories and terms to the Skill Flip glossary",
    type: "product-design",
    status: "completed",
    description: "add new categories and terms",
    path: ".maister/tasks/product-design/2026-07-13-add-new-categories-terms",
    current_activity: null
  },
  characteristics: {
    is_greenfield: false,
    is_enhancement: true,
    is_ui_focused: true,
    is_backend: false,
    is_complex: true,
    is_simple: false
  },
  phases: [
    { id: "phase-0", name: "Initialize, gather context & detect characteristics", icon_hint: "analysis", status: "completed", started: "2026-07-13T11:56:17Z", completed: "2026-07-13T12:09:41Z", skip_reason: null, summary: "3 context files catalogued: dna-mapa.md (architecture mind-map), microservice-patterns.md, system-design terms.md. Raw notes, not curated entries; overlap with existing categories flagged.", decisions: [{decision: "Characteristics confirmed: enhancement, not UI-focused, complex", rationale: "User confirmed detected read: existing codebase, content/taxonomy-driven (not a UI redesign request), complex due to multiple candidate categories and overlapping raw source material"}], risks: ["Source material is raw/unstructured, not ready-made glossary entries", "Overlap between the 3 files and with existing DevOps/Cloud Engineering/Software Engineering categories"], artifacts: [{path: "context/dna-mapa.md", label: "Architecture mind-map (source)", html: null}, {path: "context/microservice-patterns.md", label: "Microservices patterns (source)", html: null}, {path: "context/system-design terms.md", label: "System design terms (source)", html: null}], gate: {question: "Confirm detected characteristics?", answer: "Correct, proceed"} },
    { id: "phase-1", name: "Synthesize all context sources", icon_hint: "analysis", status: "completed", started: "2026-07-13T12:09:41Z", completed: "2026-07-13T12:29:43Z", skip_reason: null, summary: "Category taxonomy is flat, hand-synced (3 unsynced copies), fully data-driven rendering — code changes small/low-risk. Real cost is curating ~90-110 raw, overlapping concepts from 3 heterogeneous sources (one Polish 585-line mind-map, two bare English term lists). Category naming/grouping unresolved.", decisions: [{decision: "Extend existing flat Category union/array pattern rather than a hierarchical taxonomy", rationale: "Rendering, badging, and validation are already generic/data-driven and scale to N categories with no new branching logic"}, {decision: "New categories must be appended at the end of ALL_CATEGORIES/Category, not inserted mid-list", rationale: "BrowseGrid.test.ts has order-dependent assertions tied to the current last category"}], risks: ["3 hand-maintained, unsynced copies of the category list with no compiler-enforced sync", "Overlapping concepts across the 3 source files (CQRS, circuit breaker, service discovery, distributed tracing) need dedup before curation", "dna-mapa.md is entirely in Polish, inverting the EN-primary curation workflow", "FilterBar's 5-visible+overflow chip UX was designed for 12 categories", "npm test does not run validate-glossary; only deploy-time CI catches taxonomy drift"], artifacts: [{path: "analysis/codebase-analysis.md", label: "Codebase Analysis Report", html: null}, {path: "analysis/design-context.md", label: "Design Context", html: null}], gate: {question: "Context synthesis complete, any corrections?", answer: "Looks right, proceed"} },
    { id: "phase-2", name: "Explore problem space", icon_hint: "analysis", status: "completed", started: "2026-07-13T12:29:43Z", completed: "2026-07-13T12:49:48Z", skip_reason: null, summary: "Expand the fixed 12-category taxonomy to cover architecture/microservices/system-design notes. Deliverable is taxonomy structure + curation plan + FilterBar redesign, not the full ~90-110 entries (follow-up pass).", decisions: [{decision: "Derive category boundaries from source material's own structure", rationale: "Source authors already grouped content meaningfully"}, {decision: "Enrich existing thin categories where content fits", rationale: "Avoids redundant near-duplicate categories"}, {decision: "Design-task scope is taxonomy + curation plan, not full entry curation", rationale: "Content work is substantial and shouldn't bloat the design decision"}, {decision: "is_ui_focused flipped true, Phase 7 activated", rationale: "User chose to address FilterBar chip UX as part of this task"}], risks: ["Exact new category names/boundaries not yet decided", "Overlapping concepts across sources still need per-concept dedup", "PL-source curation discipline must be documented clearly"], artifacts: [{path: "analysis/problem-statement.md", label: "Problem Statement", html: null}], gate: {question: "Does the problem statement capture the task correctly?", answer: "Approve and continue"} },
    { id: "phase-3", name: "Explore users & personas", icon_hint: "analysis", status: "completed", started: "2026-07-13T12:49:48Z", completed: "2026-07-13T12:59:35Z", skip_reason: null, summary: "Two personas: Interview-Prep Curator (primary, app owner) and Portfolio Visitor (secondary, recruiter evaluating breadth). Learn Mode's existing filter-scoping already satisfies isolated-drilling need.", decisions: [{decision: "Learn Mode's existing filter-scoping already satisfies isolated-drilling need", rationale: "Shipped 2026-07-05 (commit 7dbb9af) — no new Learn Mode feature required"}, {decision: "Include Portfolio Visitor persona despite content-only task", rationale: "Category naming is user-facing and affects signaled expertise"}], risks: [], artifacts: [{path: "analysis/personas.md", label: "Personas", html: null}], gate: {question: "Do these persona cards capture the right users and journeys?", answer: "Approve personas and continue"} },
    { id: "phase-4", name: "Generate design alternatives", icon_hint: "plan", status: "completed", started: "2026-07-13T12:59:35Z", completed: "2026-07-13T13:09:08Z", skip_reason: null, summary: "4 decision areas generated: taxonomy structure (3 alts, recommends 6 new/18 total), cross-source dedup (3 alts, recommends merge-into-richest), FilterBar UX (5 alts, recommends symmetric collapse + count bump), curation sequencing (3 alts, recommends hybrid upfront-then-incremental).", decisions: [], risks: ["Category-boundary judgment calls remain (e.g. Bounded Contexts placement)", "Actual entry counts per new category unknown until curation", "Service discovery has granularity mismatch across sources", "FilterBar recommendation conditional on final taxonomy decision"], artifacts: [{path: "analysis/alternatives.md", label: "Solution Alternatives", html: "analysis/alternatives.html"}], gate: null },
    { id: "phase-5", name: "Converge on design direction", icon_hint: "plan", status: "completed", started: "2026-07-13T13:09:08Z", completed: "2026-07-13T13:21:42Z", skip_reason: null, summary: "14 total categories (2 new). Overlaps kept separate w/ cross-references. FilterBar: symmetric collapse + count 7-8. Curation batch-by-source-file, Polish last.", decisions: [{decision: "Taxonomy: Alternative A (2 new/14 total) over recommended B", rationale: "Prioritized FilterBar simplicity and lower hand-sync overhead"}, {decision: "Dedup: keep separate w/ cross-references over recommended merge", rationale: "Prioritized preserving each source's distinct framing"}, {decision: "FilterBar UX: symmetric collapse + raised count", rationale: "Cheapest fix for the named pain point, proportionate to 14-category outcome"}, {decision: "Curation sequencing: batch by source file, Polish last", rationale: "Easy-to-hard ordering, isolates Polish-source discipline"}], risks: ["Dangling cross-reference risk until final Polish batch lands", "No UI affordance exists for cross-references today", "Microservices & Distributed Systems likely becomes the largest category", "Exact boundaries within the 2 new categories still need finalizing"], artifacts: [{path: "analysis/design-decisions.md", label: "Design Decisions", html: "analysis/design-decisions.html"}], gate: {question: "Does this overall direction look right to proceed to specification?", answer: "Approve direction, continue to specification"} },
    { id: "phase-6", name: "Specify features section-by-section", icon_hint: "spec", status: "completed", started: "2026-07-13T13:21:42Z", completed: "2026-07-13T13:52:12Z", skip_reason: null, summary: "6 sections, all approved: taxonomy structure (14 cats), dedup/cross-reference handling, code changes, FilterBar UX redesign, curation plan, acceptance criteria. Implementation-ready.", decisions: [{decision: "14 categories total, Software Architecture then Microservices & Distributed Systems appended", rationale: "Thematically adjacent placement"}, {decision: "Cross-references are plain-text notes, no schema/UI changes", rationale: "Minimum-viable, matches scope boundary"}, {decision: "VISIBLE_CATEGORY_CHIP_COUNT raised to 7", rationale: "Even split at 14 total categories"}, {decision: "Expand/collapse state does not persist", rationale: "Presentational, distinct from persisted filter state"}], risks: ["Dangling cross-reference risk mitigated by one-time audit, not yet validated", "Illustrative entry counts are estimates, not commitments"], artifacts: [{path: "analysis/feature-spec.md", label: "Feature Specification", html: "analysis/feature-spec.html"}], gate: {question: "Specification complete, continue to Visual Prototyping?", answer: "Yes, continue to Phase 7"} },
    { id: "phase-7", name: "Create visual prototypes", icon_hint: "code", status: "completed", started: "2026-07-13T13:52:12Z", completed: "2026-07-13T14:03:33Z", skip_reason: null, summary: "Interactive FilterBar mockup at 14 categories, built with real theme tokens. Symmetric collapse verified programmatically. Approved after live browser review.", decisions: [{decision: "FilterBar mockup approved as-is", rationale: "User confirmed layout and interactions after live testing"}], risks: [], artifacts: [{path: "analysis/mockups/browse-filterbar-at-14-categories.html", label: "Browse — FilterBar at 14 Categories", html: "analysis/mockups/browse-filterbar-at-14-categories.html"}], gate: {question: "Does the FilterBar redesign mockup look right?", answer: "Approve all screens and continue"} },
    { id: "phase-8", name: "Review & hand off product brief", icon_hint: "done", status: "completed", started: "2026-07-13T14:03:33Z", completed: "2026-07-13T14:07:40Z", skip_reason: null, summary: "Layered product brief assembled and approved: 14-category taxonomy, dedup policy, FilterBar redesign, 3-batch curation plan. Ready for /maister:development handoff.", decisions: [{decision: "Product brief approved as final", rationale: "User approved after reviewing all layers"}], risks: [], artifacts: [{path: "outputs/product-brief.md", label: "Product Brief", html: null}], gate: {question: "Approve product brief?", answer: "Approve product brief"} }
  ],
  verification: { status: null, issues: [], fixes: [], reverify_count: 0 }
}
