window.MAISTER_DATA = {
  generated: "2026-07-01T14:31:54Z",
  task: {
    title: "Skill Flip - Engineering Lexicon (Implementation)",
    type: "development",
    status: "in_progress",
    description: "Implement the Skill Flip engineering lexicon flashcard app per the approved product-design brief: Vite + vanilla TypeScript, client-only, glossary data model, single-card flip/learn-mode component + browse grid, bucketed weighted-random learn algorithm, documented AI content pipeline, GitHub Pages deployment.",
    path: ".maister/tasks/development/2026-07-01-skill-flip-engineering-lexicon",
    current_activity: "Executing implementation"
  },
  characteristics: {
    has_reproducible_defect: false,
    modifies_existing_code: false,
    creates_new_entities: true,
    involves_data_operations: true,
    ui_heavy: true
  },
  phases: [
    { id: "phase-1", name: "Analyze codebase & clarify requirements", icon_hint: "analysis", status: "completed", started: "2026-07-01T13:50:39Z", completed: "2026-07-01T13:59:22Z", skip_reason: null, summary: "Confirmed clean greenfield state (no source code, no git repo) with a fully implementation-ready 8-section feature spec and 4 validated mockups already in place.", decisions: [{decision: "Initialize git now, as part of this build", rationale: "Needed for the GitHub Actions deploy workflow"}, {decision: "Target repo aib-projekt/skill-flip", rationale: "Matches GitHub org referenced for the visual palette"}, {decision: "Author a starter subset (~15-20 terms) this pass", rationale: "Keeps this pass focused on app + pipeline; full authoring deferred"}, {decision: "MIT license", rationale: "Standard permissive default"}], risks: [], artifacts: [{path: "analysis/codebase-analysis.md", label: "Codebase Analysis", html: null}, {path: "analysis/clarifications.md", label: "Clarifications", html: null}], gate: null },
    { id: "phase-2", name: "Analyze gaps & clarify scope", icon_hint: "analysis", status: "completed", started: "2026-07-01T13:59:22Z", completed: "2026-07-01T14:07:57Z", skip_reason: null, summary: "Pure greenfield build against a complete spec — only gap found: mockups show a Learn/Browse tab bar with no described implementation mechanism. Resolved via decision gate (AppShell.ts manual view-swap). Data lifecycle 100% complete, no dead ends.", decisions: [{decision: "AppShell.ts, manual view-swap for Learn/Browse tab navigation", rationale: "Matches spec's no-framework discipline; no deep-linkable sub-states"}], risks: [], artifacts: [{path: "analysis/gap-analysis.md", label: "Gap Analysis", html: null}, {path: "analysis/scope-clarifications.md", label: "Scope Clarifications", html: null}], gate: {question: "Continue to Phase 4?", answer: "Yes, continue"} },
    { id: "phase-3", name: "Write failing test (TDD Red)", icon_hint: "code", status: "skipped", started: null, completed: null, skip_reason: "has_reproducible_defect=false — new feature build, no TDD red/green gate", summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-4", name: "Generate UI mockups", icon_hint: "spec", status: "skipped", started: null, completed: null, skip_reason: "analysis/design-context/mockups/ already populated from product-design handoff — no ASCII mockup regeneration needed", summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-5", name: "Gather requirements & create specification", icon_hint: "spec", status: "completed", started: "2026-07-01T14:09:17Z", completed: "2026-07-01T14:16:25Z", skip_reason: null, summary: "Ship a deployed, portfolio-quality client-only flashcard app with flip-card Learn Mode, Browse/Filter/Search, and a documented content pipeline. Covers all 8 authoritative feature-spec sections plus AppShell.ts.", decisions: [{decision: "Follow feature-spec.md's 8 sections verbatim", rationale: "already implementation-ready and mockup-validated"}, {decision: "Add AppShell.ts for manual Learn/Browse view-swap", rationale: "resolves gap-analysis finding"}, {decision: "Ship Java-only ~15-20 term starter subset", rationale: "per Phase 1 clarification"}, {decision: "Vitest as test framework", rationale: "pairs with Vite, zero extra config"}], risks: ["Full 150-term content authoring remains a follow-up pass", "Badge-color mapping, mastery banner, reset-progress placement are implementation-time defaults"], artifacts: [{path: "implementation/spec.md", label: "Specification", html: "implementation/spec.html"}], gate: null },
    { id: "phase-6", name: "Audit specification", icon_hint: "verify", status: "completed", started: "2026-07-01T14:16:25Z", completed: "2026-07-01T14:23:57Z", skip_reason: null, summary: "Independent audit: pass-with-concerns (0 critical, 1 high, 5 medium, 4 low). High/Medium findings (debounce timing dropped; AppShell/topbar ownership vs. mockup HTML) patched into spec.md before proceeding.", decisions: [{decision: "Patched spec.md: 200ms debounce, AppShell owns only bottom tab bar, progress-stats in both topbars", rationale: "Cheaper to fix at spec stage than after implementation"}], risks: ["Per-category badge-color mapping: 9 of 12 categories have zero mockup precedent (Low)", "Reset-progress confirmation copy left to implementation discretion (Low)"], artifacts: [{path: "verification/spec-audit.md", label: "Specification Audit", html: null}], gate: null },
    { id: "phase-7", name: "Plan implementation", icon_hint: "plan", status: "completed", started: "2026-07-01T14:23:57Z", completed: "2026-07-01T14:31:54Z", skip_reason: null, summary: "9 task groups, 52 steps, 34-58 tests across 6 parallel waves. All 4 mockup screens + 5 shared components covered per visual-coverage.md.", decisions: [{decision: "9 task groups, parallel wave dispatch", rationale: "Dependency graph allows Groups 2/3/7 and 4/5 to run concurrently"}, {decision: "progress-stats computation split from rendering", rationale: "Matches spec-audit-corrected AppShell/topbar ownership"}], risks: ["theme.css and package.json appended by multiple groups — must be serialized even when concurrent", "TaskCreate/TaskUpdate unavailable to planner subagent — markdown checkboxes are the resumable tracking source"], artifacts: [{path: "implementation/implementation-plan.md", label: "Implementation Plan", html: "implementation/implementation-plan.html"}, {path: "implementation/visual-coverage.md", label: "Visual Coverage", html: null}], gate: null },
    { id: "phase-8", name: "Execute implementation", icon_hint: "code", status: "in_progress", started: "2026-07-01T14:31:54Z", completed: null, skip_reason: null, summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-9", name: "Verify test passes (TDD Green)", icon_hint: "verify", status: "pending", started: null, completed: null, skip_reason: null, summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-10", name: "Prompt verification options", icon_hint: "verify", status: "pending", started: null, completed: null, skip_reason: null, summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-11", name: "Verify implementation & resolve issues", icon_hint: "verify", status: "pending", started: null, completed: null, skip_reason: null, summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-12", name: "Run E2E tests", icon_hint: "verify", status: "pending", started: null, completed: null, skip_reason: null, summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-13", name: "Generate user documentation", icon_hint: "docs", status: "pending", started: null, completed: null, skip_reason: null, summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-14", name: "Finalize workflow", icon_hint: "done", status: "pending", started: null, completed: null, skip_reason: null, summary: null, decisions: [], risks: [], artifacts: [], gate: null }
  ],
  verification: { status: null, issues: [], fixes: [], reverify_count: 0 }
}
