window.MAISTER_DATA = {
  generated: "2026-07-01T13:47:09Z",
  task: {
    title: "Skill Flip - Engineering Lexicon",
    type: "product-design",
    status: "completed",
    description: "Personal interactive HTML flashcard lexicon of Java/Backend engineering terms (Regular/Senior), built from an Engineering Ladder taxonomy. Dual purpose: personal study tool + public GitHub portfolio piece.",
    path: ".maister/tasks/product-design/2026-07-01-lexicon-engineering-terms",
    current_activity: null
  },
  characteristics: {
    is_greenfield: true,
    is_enhancement: false,
    is_ui_focused: true,
    is_backend: false,
    is_complex: true,
    is_simple: false,
    complexity_level: "complex"
  },
  phases: [
    { id: "phase-0", name: "Initialize, gather context & detect characteristics", icon_hint: "analysis", status: "completed", started: "2026-07-01T10:18:57Z", completed: "2026-07-01T10:32:49Z", skip_reason: null, summary: "Greenfield, UI-focused, no backend, complex. Context files (Skill Flip.md brief + Engineering Ladder.md taxonomy) provided.", decisions: [], risks: [], artifacts: [], gate: {question: "Confirm detected characteristics?", answer: "Correct, proceed with these"} },
    { id: "phase-1", name: "Synthesize all context sources", icon_hint: "analysis", status: "completed", started: "2026-07-01T10:32:49Z", completed: "2026-07-01T10:33:58Z", skip_reason: null, summary: "Personal client-only flashcard app for engineering terms, sourced from a 12-category Engineering Ladder taxonomy. Stack undecided; content curation approach undecided.", decisions: [{decision: "Treat as greenfield, client-only design (no backend)", rationale: "No existing codebase/docs; user's requirements (GH Pages, static JSON + localStorage) imply a static site"}], risks: ["Tech stack undecided: vanilla JS vs Vite vs Claude's suggestion — needs a convergence decision (Phase 5)", "Scope of full-text search unclear: term only, or description/translations too?", "Content volume/curation approach unknown: transcribe Engineering Ladder verbatim vs curate a subset with authored definitions", "Portfolio audience (recruiters/visitors) affects README tone and onboarding, not just personal use"], artifacts: [{path: "analysis/design-context.md", label: "Unified Design Context", html: null}], gate: {question: "Context synthesis complete. Any corrections or additions?", answer: "Looks right, proceed"} },
    { id: "phase-2", name: "Explore problem space", icon_hint: "analysis", status: "completed", started: "2026-07-01T11:23:14Z", completed: "2026-07-01T11:42:17Z", skip_reason: null, summary: "Mobile-first, client-only flashcard app; both personal-study and portfolio goals equal priority; content curated via AI-assisted pass; weighted learn-mode resurfacing; visual identity from AiB Projekt GitHub avatar palette.", decisions: [{decision: "Curate & rewrite content via AI-assisted pass rather than transcribe verbatim", rationale: "Ladder bullets are ability statements, not term+definition pairs"}, {decision: "Mobile-first design", rationale: "Actual study sessions happen on mobile during downtime"}, {decision: "Lightweight weighted resurfacing for learn mode", rationale: "More than a stat counter, but not full SRS complexity"}, {decision: "Visual identity from AiB Projekt GitHub avatar palette", rationale: "Explicit user direction"}], risks: ["Weighted resurfacing algorithm needs concrete, simple definition during spec", "AI content-generation pipeline needs clear boundary from shipped app runtime", "~150-term content authoring effort is larger than the app-building effort"], artifacts: [{path: "analysis/problem-statement.md", label: "Problem Statement", html: null}], gate: {question: "Problem space explored. Continue to Phase 3?", answer: "Yes, continue"} },
    { id: "phase-3", name: "Explore users & personas", icon_hint: "analysis", status: "completed", started: "2026-07-01T11:42:17Z", completed: "2026-07-01T11:47:35Z", skip_reason: null, summary: "Two personas: the Creator (primary, short frequent mobile study sessions) and the Recruiter/Visitor (secondary, immediate interactive demo on arrival).", decisions: [{decision: "Learn Mode resumes instantly, no configuration step", rationale: "Creator's usage pattern is short frequent bursts"}, {decision: "Live GitHub Pages demo is the primary landing experience for Recruiter persona", rationale: "Recruiters try the interactive demo immediately"}], risks: [], artifacts: [{path: "analysis/personas.md", label: "Personas", html: null}], gate: {question: "Personas defined. Continue to Idea Generation?", answer: "Yes, continue"} },
    { id: "phase-4", name: "Generate design alternatives", icon_hint: "plan", status: "completed", started: "2026-07-01T11:47:35Z", completed: "2026-07-01T11:52:32Z", skip_reason: null, summary: "4 decision areas, 14 alternatives: tech stack (Vite+TS), learn-mode algorithm (bucketed weighted-random), interaction model (single-card+controls), content pipeline (documented).", decisions: [], risks: [], artifacts: [{path: "analysis/alternatives.md", label: "Solution Exploration", html: "analysis/alternatives.html"}], gate: null },
    { id: "phase-5", name: "Converge on design direction", icon_hint: "plan", status: "completed", started: "2026-07-01T11:52:32Z", completed: "2026-07-01T12:06:33Z", skip_reason: null, summary: "Converged on Vite+TS stack, bucketed weighted-random learn algorithm, single-card+grid hybrid interaction model, documented content pipeline.", decisions: [{decision: "Tech stack: Vite + vanilla TypeScript, no framework", rationale: "Modern tooling signal + type safety without framework overhead"}, {decision: "Learn-mode algorithm: bucketed weighted-random draw", rationale: "Matches explicit not-binary, not-full-SRS constraint"}, {decision: "Interaction model: single-card-with-controls + flippable grid hybrid", rationale: "One shared component + discoverable affordances + coverage-scanning for browse"}, {decision: "Content pipeline: documented prompt + rubric + validation script", rationale: "Makes curation quality demonstrable, catches data bugs"}], risks: ["Graduation threshold N needs a concrete default pinned in specification", "Single-card/grid hybrid state-sharing needs to be defined in specification", "Validation-script scope must stay capped, not grow into a full CLI"], artifacts: [{path: "analysis/design-decisions.md", label: "Design Decisions", html: "analysis/design-decisions.html"}], gate: {question: "Design direction approved. Continue to Phase 6?", answer: "Yes, continue"} },
    { id: "phase-6", name: "Specify features section-by-section", icon_hint: "spec", status: "completed", started: "2026-07-01T12:10:33Z", completed: "2026-07-01T12:39:18Z", skip_reason: null, summary: "8-section implementation-ready spec, depth-verified. Revised during Phase 7 mockup review to add descriptionPl (full Polish definition translation, not just term).", decisions: [{decision: "GlossaryEntry schema: id/term/description/translationPl/descriptionPl/category/level", rationale: "Validation-script-enforced, not runtime-enforced; descriptionPl added after mockup review"}, {decision: "Translation hidden behind separate (i) toggle, reveals term + full definition", rationale: "User feedback during Section 2 review — keeps English definition primary"}, {decision: "Bucketed weighted-random draw: weights 4/2/1, graduation after 2 consecutive know-marks", rationale: "Concrete pinning of the algorithm left open after Phase 5"}, {decision: "Added a non-avatar terracotta accent color for dont-know state", rationale: "Avatar palette had no warning/attention color; flagged and approved"}], risks: ["Per-category badge-color assignment left as implementation detail", "No special UI for 100% mastery edge case (nice-to-have)", "License choice for README left to creator"], artifacts: [{path: "analysis/feature-spec.md", label: "Feature Specification", html: "analysis/feature-spec.html"}], gate: {question: "Specification complete. Continue to Phase 7?", answer: "Yes, continue"} },
    { id: "phase-7", name: "Create visual prototypes", icon_hint: "code", status: "completed", started: "2026-07-01T12:39:18Z", completed: "2026-07-01T13:22:35Z", skip_reason: null, summary: "4 mockups via visual companion: Learn Mode card front/back, Browse filter+grid, Browse empty state. Fixed a card-back overflow bug and a PL-translation scope gap (now covers full definition, not just term).", decisions: [{decision: "Card-back layout grows with content instead of a fixed aspect-ratio box", rationale: "Fixed-ratio box caused longer definitions to overflow into controls below"}, {decision: "descriptionPl added to GlossaryEntry schema", rationale: "Mockup review surfaced term-only translation was an unconfirmed assumption"}], risks: [], artifacts: [{path: "analysis/mockups/learn-mode-card-front.html", label: "Learn Mode — Card Front", html: "analysis/mockups/learn-mode-card-front.html"}, {path: "analysis/mockups/learn-mode-card-back-flipped.html", label: "Learn Mode — Card Back (Flipped)", html: "analysis/mockups/learn-mode-card-back-flipped.html"}, {path: "analysis/mockups/browse-filter-and-grid.html", label: "Browse — Filter and Grid", html: "analysis/mockups/browse-filter-and-grid.html"}, {path: "analysis/mockups/browse-empty-state.html", label: "Browse — Empty State", html: "analysis/mockups/browse-empty-state.html"}], gate: {question: "Visual prototyping complete. Continue to Phase 8?", answer: "Yes, continue"} },
    { id: "phase-8", name: "Review & hand off product brief", icon_hint: "done", status: "completed", started: "2026-07-01T13:26:59Z", completed: "2026-07-01T13:47:09Z", skip_reason: null, summary: "Layered product brief assembled (Core Brief, Personas, Design Decisions, Mockup References, References) and approved on first review. Visual companion server shut down.", decisions: [], risks: [], artifacts: [{path: "outputs/product-brief.md", label: "Product Brief", html: "outputs/product-brief.html"}], gate: {question: "Approve product brief?", answer: "Approve product brief"} }
  ],
  verification: { status: null, issues: [], fixes: [], reverify_count: 0 }
}
